from Sources import AppComposer

# Make Application
MPEG4 = AppComposer.Application(AppName = "MPEG4")
Applications = [MPEG4]

# Make Threads
VU = AppComposer.Thread()
AU = AppComposer.Thread()
MedCPU = AppComposer.Thread()
RAST = AppComposer.Thread()
SDRAM = AppComposer.Thread()
SRAM1 = AppComposer.Thread()
SRAM2 = AppComposer.Thread()
IDCT = AppComposer.Thread()
ADSP = AppComposer.Thread()
UpSamp = AppComposer.Thread()
BAB = AppComposer.Thread()
RISC = AppComposer.Thread()

# Add Threads to applications
MPEG4.addThread(VU)
MPEG4.addThread(AU)
MPEG4.addThread(MedCPU)
MPEG4.addThread(RAST)
MPEG4.addThread(SDRAM)
MPEG4.addThread(SRAM1)
MPEG4.addThread(SRAM2)
MPEG4.addThread(IDCT)
MPEG4.addThread(ADSP)
MPEG4.addThread(UpSamp)
MPEG4.addThread(BAB)
MPEG4.addThread(RISC)

# Add targets to Threads (Bandwidth must be in Megabits/second)
VU.addTarget(AppComposer.Target(TargetThread = SDRAM, Bandwidth = 190))
AU.addTarget(AppComposer.Target(TargetThread = SDRAM, Bandwidth = 0.5))
MedCPU.addTarget(AppComposer.Target(TargetThread = SDRAM, Bandwidth = 60))
MedCPU.addTarget(AppComposer.Target(TargetThread = SRAM1, Bandwidth = 40))
RAST.addTarget(AppComposer.Target(TargetThread = SDRAM, Bandwidth = 600))
RAST.addTarget(AppComposer.Target(TargetThread = SRAM1, Bandwidth = 40))
SDRAM.addTarget(AppComposer.Target(TargetThread = VU, Bandwidth = 190))
SDRAM.addTarget(AppComposer.Target(TargetThread = AU, Bandwidth = 0.5))
SDRAM.addTarget(AppComposer.Target(TargetThread = MedCPU, Bandwidth = 60))
SDRAM.addTarget(AppComposer.Target(TargetThread = RAST, Bandwidth = 600))
SDRAM.addTarget(AppComposer.Target(TargetThread = ADSP, Bandwidth = 0.5))
SDRAM.addTarget(AppComposer.Target(TargetThread = UpSamp, Bandwidth = 910))
SDRAM.addTarget(AppComposer.Target(TargetThread = BAB, Bandwidth = 32))
SRAM1.addTarget(AppComposer.Target(TargetThread = MedCPU, Bandwidth = 40))
SRAM1.addTarget(AppComposer.Target(TargetThread = RAST, Bandwidth = 40))
SRAM2.addTarget(AppComposer.Target(TargetThread = IDCT, Bandwidth = 250))
SRAM2.addTarget(AppComposer.Target(TargetThread = UpSamp, Bandwidth = 670))
SRAM2.addTarget(AppComposer.Target(TargetThread = BAB, Bandwidth = 173))
SRAM2.addTarget(AppComposer.Target(TargetThread = RISC, Bandwidth = 500))
IDCT.addTarget(AppComposer.Target(TargetThread = SRAM2, Bandwidth = 250))
ADSP.addTarget(AppComposer.Target(TargetThread = SDRAM, Bandwidth = 0.5))
UpSamp.addTarget(AppComposer.Target(TargetThread = SDRAM, Bandwidth = 910))
UpSamp.addTarget(AppComposer.Target(TargetThread = SRAM2, Bandwidth = 670))
BAB.addTarget(AppComposer.Target(TargetThread = SDRAM, Bandwidth = 32))
BAB.addTarget(AppComposer.Target(TargetThread = SRAM2, Bandwidth = 173))
RISC.addTarget(AppComposer.Target(TargetThread = SRAM2, Bandwidth = 500))
